### ISSUE TITLE
How do you change the font size?

### ISSUE THREAD

**Issue by Cois19** [jgreco/mpv-youtube-quality#23]
I know it has something to do with the conf file but I'm not sure exactly what to change inside

**Comment by Cois19** [comment]
nevermind I found it

for example:
`style_ass_tags={\\fnUbuntu\\fs40\\bord1}`

**Comment by Darkmaster006** [comment]
>  `style_ass_tags={\\fnUbuntu\\fs40\\bord1}`

@Cois19 Where did you write this? I put it in youtube-quality.conf, in line 20 it says "scale_playlist_by_window=no" and I changed it to:
scale_playlist_by_window=yes
style_ass_tags={\\fnmonospace\\fs8}

I tried with yours too, but I can't get it to work. Any ideas? Thank you.

**Comment by Cois19** [comment]
you are missing "\", look carefully at my example.

**Comment by keeganjk** [comment]
This works, but is there a way to scale the size according to how many options there are, e.g. using the largest size that will fit all options in the window?
