### ISSUE TITLE
Conflict with mpv_thumbnail_script

### ISSUE THREAD

**Issue by salastro** [jgreco/mpv-youtube-quality#25]
> PLEASE NOTE: This conflicts with other scripts that modify the OSC, such as TheAMM's excellent mpv_thumbnail_script. Merging this OSC modification with that script or others is certainly possible, but is left as an exercise for the user...

I do not know lua, I have no plans to learn it in the near feature, I just want a solution to this problem.

**Comment by zydezu** [comment]
Average github eliteism, seriously patronising for no reason ?
