### ISSUE TITLE
Audio only stream selection [enhancement]

### ISSUE THREAD

**Issue by plissken1138** [jgreco/mpv-youtube-quality#30]
If possible, add audio only stream selection.

**Comment by thansk** [comment]
I've made a fork with audio support: https://github.com/thansk/mpv-youtube-quality

**Comment by christoph-heinrich** [comment]
In [my fork](https://github.com/christoph-heinrich/mpv-quality-menu) there a video and an audio menu, both of which contain a "None" option. Setting video to "None" will let you stream audio only.
